name: Production Build
run-name: ${{ github.actor }} triggered a production build

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build production Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: smtp:prod-build
          cache-from: type=gha
          cache-to: type=gha,mode=max
